Repository pablotrinidad/platzigram, pull requests merged in 2018-10, with the labels that each got.

#8 Add requirements file with last version of django
  README.md
  requirements.txt
Labels: hacktoberfest

#10 Extra login social with facebook
  platzigram/settings.py
  platzigram/urls.py
  requirements.txt
  templates/users/login.html
  templates/users/signup.html
  users/models.py
Labels: enhancement, hacktoberfest

#16 Cleaning requirements.txt/Limpiando requirements.txt
  requirements.txt
Labels: enhancement, good first issue, hacktoberfest
